# Generated by Django 5.2.1 on 2025-05-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='areaId',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
