# Generated by Django 5.2.1 on 2025-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inventoryproduct_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
