# Generated by Django 5.2.1 on 2025-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inventoryproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
