# Generated by Django 5.2.1 on 2025-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orderitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
